# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /c/dev/RetroZilla/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/local/bin:/c/dev/buildtools/retrozilla-build/src/wget:/c/dev/buildtools/retrozilla-build/src/7zip:/c/dev/buildtools/retrozilla-build/src/blat261/full:/c/dev/buildtools/retrozilla-build/src/python:/c/dev/buildtools/retrozilla-build/src/svn-win32-1.6.3/bin:/c/dev/buildtools/retrozilla-build/src/upx203w:/c/dev/buildtools/retrozilla-build/src/emacs-22.3/bin:/c/dev/buildtools/retrozilla-build/src/info-zip:/c/dev/buildtools/retrozilla-build/src/nsis-2.22:/c/dev/buildtools/retrozilla-build/src/nsis-2.33u:/c/dev/buildtools/retrozilla-build/src/nsis-2.46u:/c/dev/buildtools/retrozilla-build/src/wix-351728:/c/dev/buildtools/retrozilla-build/src/hg:/c/dev/buildtools/retrozilla-build/src/python/Scripts:/c/dev/buildtools/retrozilla-build/src/kdiff3:.:/usr/local/bin:/mingw/bin:/bin:/c/PROGRA~2/MICROS~2/Common/msdev98/BIN:/c/PROGRA~2/MICROS~2/VC98/BIN:/c/PROGRA~2/MICROS~2/Common/TOOLS/WINNT:/c/PROGRA~2/MICROS~2/Common/TOOLS:/c/WINDOWS/System32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/dev/buildtools/retrozilla-build/src/moztools-180compat/bin:/c/dev/buildtools/retrozilla-build/src/vim/vim72
MOZ_MAKE_FLAGS=-j4
MOZ_OBJDIR=/c/objdir/obj-sm95-release
# --target=i586-pc-msvc is used by configure (not client.mk)
# --enable-application=suite is used by configure (not client.mk)
# --enable-optimize is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --without-system-jpg is used by configure (not client.mk)
# --without-system-zlib is used by configure (not client.mk)
# --enable-extensions=default,tasks is used by configure (not client.mk)
# --enable-crypto is used by configure (not client.mk)
# --enable-svg is used by configure (not client.mk)
# --enable-canvas is used by configure (not client.mk)
